In [1]:
import numpy as np
print(np.__version__)

2.2.6


## Creating Arrays

### From Lists

In [14]:
import numpy as np

#1D array
arr1d = np.array([1,2,3,4,5])
print("1D Array",arr1d)

#2D array
arr2d = np.array([[1,2,3],[8,9,11]])
print("2D Array", arr2d)

#3D array

arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d.shape)  # Output: (2, 2, 2)

arr3d = np.array([
    [[1,2,3],[3,4,5],[3,4,1]],
    [[5,6,1],[7,8,1], [3,4,1]]
])

print("3D Array", arr3d.shape)

1D Array [1 2 3 4 5]
2D Array [[ 1  2  3]
 [ 8  9 11]]
3D Array (2, 3, 3)


## Built in Array Creation

In [22]:
# zeros
zeros = np.zeros((3,4))
print(zeros)

#Ones
ones = np.ones((2,3))
print(ones)

#Full (Fill with Specific Values )
full = np.full((2,2),7)
print(full)

# Identity matrix

Identity = np.eye(3)
print(Identity)

#Range 
range_arr = np.arange(0,10,2)
print (range_arr) #output: [0 2 4 6 8 ]

#Linespace ( evenly spaced )

linspace_arr = np.linspace(0,1,5) 
print (linspace_arr) #output [ 0. 0.25 0.5 0.75 1. ]

#Random 
random_arr = np.random.rand(3,3) # will 3x3 matix with random values
print(random_arr)

random_int = np.random.randint( 0,10, (3,3)) # random integers
print(random_int)

#Normal Distribution

normal = np.random.normal (0, 1,(3,3)) #mean=0, std=1
print(normal)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.63604472 0.75585809 0.31987003]
 [0.02475911 0.64009116 0.99786791]
 [0.32719842 0.5066539  0.72109344]]
[[6 0 7]
 [9 5 5]
 [0 6 6]]
[[ 1.01548026  1.43216725 -1.85588599]
 [ 1.9051402  -0.73169613 -0.16342532]
 [-0.91457205 -2.09121322  0.3096587 ]]


## Array Attributes and Methods

### Array Attributes

Properties that describe an array's Structure

In [24]:
arr = np.array(
    [ [1,2,3], 
      [4,5,6]
    ])
# Shape - dimensions of the array
print("Shape : ", arr.shape) # Output: (2,3) 2 row, 3 col

# Size - total number of elements
print ("Size : ", arr.size) # Output : 6

# Number of dimensions
print("Dimension", arr.ndim) #output: 2

# Data Type
print("Data Type: ", arr.dtype) 

#Bytes per element
print("Bytes per element", arr.itemsize)

#Total bytes
print("Total Bytes: ", arr.nbytes)

Shape :  (2, 3)
Size :  6
Dimension 2
Data Type:  int64
Bytes per element 8
Total Bytes:  48


### Array Methods
Quick mathematical operations on arrays:

In [26]:
arr = np.array([1, 2, 3, 4, 5])

# Sum of all elements
print(arr.sum())      # Output: 15

# Mean (average)
print(arr.mean())     # Output: 3.0

# Standard deviation
print(arr.std())      # Output: 1.414...

# Variance
print(arr.var())      # Output: 2.0

# Minimum value
print(arr.min())      # Output: 1

# Maximum value
print(arr.max())      # Output: 5

# Index of minimum
print(arr.argmin())   # Output: 0

# Index of maximum
print(arr.argmax())   # Output: 4

# For 2D arrays - specify axis
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

# Sum along columns (axis=0)
print(arr2d.sum(axis=0))  # Output: [5 7 9]

# Sum along rows (axis=1)
print(arr2d.sum(axis=1))  # Output: [6 15]

# Mean along columns
print(arr2d.mean(axis=0))  # Output: [2.5 3.5 4.5]

15
3.0
1.4142135623730951
2.0
1
5
0
4
[5 7 9]
[ 6 15]
[2.5 3.5 4.5]


### Key Concept: NumPy arrays vs Python lists

**NumPy arrays**: Homogeneous (same data type), faster, less memory

**Python lists**: Heterogeneous (different types), more flexible, slower

In [27]:
# Python list
python_list = [1, 2, 3, "hello", 5.5]  # Can mix types

# NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])  # All same type
# numpy_array = np.array([1, 2, 3, "hello"])  # Converts all to strings!

## <u> Reshaping and Resizing </u>